language:
    - php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - export PATH=~/.composer/vendor/bin:$PATH
    - composer self-update
    - composer global require "squizlabs/php_codesniffer=*"
    - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Wordpress
    - phpenv rehash
    - phpcs --config-set installed_paths ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/WordPress
    - phpcs -i
    - nvm install 0.12
    - npm install

script:
    - phpcs --standard=WordPress-Core . --extensions=php
    - gulp

notifications:
    slack: sqweb:M0hKi2sdzb1VxoxtMeo4F3lh
    email: false
