language:
    - php

php:
    - 5.5
    - 5.6

before_script:
    - pear config-set auto_discover 1
    - pear install PHP_CodeSniffer
    - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    - phpenv rehash
    - phpcs --config-set installed_paths $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    - phpcs -i

script:
    - phpcs --standard=WordPress-Core . --extensions=php
